# Generated by Django 3.0.7 on 2020-07-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='units',
        ),
        migrations.AddField(
            model_name='module',
            name='units',
            field=models.ManyToManyField(to='courses.Unit'),
        ),
    ]
