# Generated by Django 3.0.7 on 2020-07-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200703_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_description',
            field=models.TextField(default='No Description Provided'),
        ),
    ]
